### ISSUE TITLE
DoesNotExist warning raises "Unknown format code" error

### ISSUE THREAD

**Issue by keturn** [outofculture/django-cached-field#4]
This line in offload_cache_recalculation https://github.com/outofculture/django-cached-field/blob/ed15ea50b6e7fe1a22d9e6796f4c4c93f1e8a733/django_cached_field/tasks.py#L31

fails with
> ValueError: Unknown format code 's' for object of type 'int'

presumably with the `obj_id` as the `int`, and apparently you can't `"{:s}".format(obj_id)` an int, even though you can totally `"%s" % (obj_id,)` one.

You can, however, `"{}".format(obj_id)`, it seems.

**Comment by outofculture** [comment]
This is fixed in master now. I need to find my pypi creds to be able to publish it.
